baseurl: "/"
languageCode: "en-us"
title: "Workflow for Statistical Analysis"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

menu:
  main:
    - name: Home
      url: ""
      weight: 1

params:
  description: "Materials for Workflow for Statistical Analysis July 2021"

